---
:global:
  :host1_username: sysadmingame
  :host1_protocol: telnet
  :host2_username: sysadmingame
  :host2_protocol: telnet
  :host3_username: root
  :domain: 'curso1617'
:cases:
- :tt_members: Jesús
  :tt_skip: true
  :number: "01"
- :tt_members: Daniel
  :number: "02"
  :username: daniel
  :lastname: perez
  :host1_password: 78835746
- :tt_members: PC03
  :tt_skip: true
  :number: "03"
- :tt_members: Bruno
  :tt_skip: true
  :number: "04"
- :tt_members: Nieves
  :tt_skip: true
  :number: "05"
- :tt_members: Raúl
  :number: "06"
  :username: raul
  :lastname: garcia
  :host1_password: 78649818f
- :tt_members: Jonay
  :number: "07"
  :username: jonay
  :lastname: barroso
  :host1_password: 78642782d
- :tt_members: Adrián
  :number: "08"
  :username: adrian
  :lastname: padron
  :host1_password: 78646783p-
- :tt_members: PC09
  :tt_skip: true
  :number: "09"
- :tt_members: PC10
  :tt_skip: true
  :number: "10"
- :tt_members: Jhuanys
  :number: "11"
  :username: jhuanys
  :lastname: gil
  :host1_password: 51204066v
- :tt_members: Jose David
  :number: "12"
  :username: jose
  :lastname: gonzalez
  :host1_password: 43384050r
- :tt_members: Eduardo
  :tt_skip: true
  :number: "13"
- :tt_members: Airam
  :number: "14"
  :username: airam
  :lastname: suarez
  :host1_password: 78645336x
- :tt_members: Javier
  :number: "15"
  :username: javier
  :lastname: gonzalez
  :host1_password: 78648313c
- :tt_members: Alexis
  :number: "16"
  :username: alexis
  :lastname: salazar
  :host1_password: 78635302g
- :tt_members: Alejandra
  :number: "17"
  :username: alejandra
  :lastname: lorenzo
  :host1_password: 78638761j
- :tt_members: PC18
  :tt_skip: true
  :number: "18"
- :tt_members: PC19
  :tt_skip: true
  :number: "19"
- :tt_members: PC20
  :tt_skip: true
  :number: "20"
- :tt_members: PC21
  :tt_skip: true
  :number: "21"
- :tt_members: Daniel Rodríguez Barreto
  :number: "22"
  :username: daniel
  :lastname: rodriguez
  :host1_password: Danillit95
